apiVersion: apps/v1
kind: Deployment
metadata:
  name: news
spec:
  selector:
    matchLabels:
      app: news
  template:
    metadata:
      labels:
        app: news
    spec:
      containers:
        - name: news
          image: rubensra/kube-news:v1
          ports:
          - containerPort: 8080
          env:
          - name: DB_DATABASE
            value: "kubenews"
          - name: DB_USERNAME
            value: "kubenews"
          - name: DB_PASSWORD
            value: "Pg#123"
          - name: DB_HOST
            value: "postgre"

---

apiVersion: v1
kind: Service
metadata:
  name: news
spec:
  selector:
    app: news
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30000
  type: NodePort

